# Generated by Django 4.0.5 on 2022-07-02 10:15

import Core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to=Core.models.user_directory_path),
        ),
    ]
