# Generated by Django 4.0.5 on 2022-07-02 11:27

import Core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=Core.models.course_directory_path),
        ),
        migrations.AlterField(
            model_name='news',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=Core.models.news_directory_path),
        ),
    ]
