# Generated by Django 4.0.5 on 2022-06-15 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_alter_news_options_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_purchased',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
