# Generated by Django 4.0.5 on 2022-06-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_payment_date_purchased'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('course', 'header')},
        ),
    ]
